### ISSUE TITLE
Generating PDF

### ISSUE THREAD

**Issue by ghost** [Linseneintopf/ygo-proxy-generator#2]
Hi, I had to correct the code to make it work with my Linux (bin/bash instead of bin/sh), but i still have problems with the PDF generation: it does not end at all, even after several minutes (20/30 min). Do you know where the problem can be?

**Comment by Linseneintopf** [comment]
Sorry for not reacting. This has been fixed with PR #8 by [safaber01](https://github.com/safaber01).
