### ISSUE TITLE
make: *** [download-images] Error 2

### ISSUE THREAD

**Issue by glennDittmann** [Linseneintopf/ygo-proxy-generator#3]
Hey, 
when executing the makefile with make in terminal (the decklist.txt was the one that came with downloading the repository. and on ubuntu 18.04) I got following error message:

user@user:~/Downloads/ygo-proxy-generator-master$ make
Downloading images
./scripts/download_images.sh: 11: ./read_decklist.sh: Syntax error: "(" unexpected
Makefile:16: recipe for target 'download-images' failed
make: *** [download-images] Error 2

Anyone knows what's wrong?
Thanks in advance,
Cheers

*edit*
Changing "bin/sh" to "bin/bash" made it work for me. As stated in the other issue.

**Comment by ilkin0** [comment]
I still have same problem. So how you solve this issue? what is changing bin/sh to bin/bash ?

**Comment by ilkin0** [comment]
> I still have same problem. So how you solve this issue? what is changing bin/sh to bin/bash ?

i even changed my ubuntu shell to bash (with chsh), it gave same error

**Comment by glennDittmann** [comment]
Hey, changing bin/sh to bin/bash just means in all the xx.sh files replacing every instance of bin/sh with bin/bash.
I still get some error too though, cause the images don't get downloaded properly.
but you can still manually download the images (as .png) and save them in the images folder. then in the tex folder update cards.tex for the cards you want to appear on the pdf (see the example how to write). then in a terminal navigate to the tex folder and type "pdflatex proxies.tex" in terminal and enter. doing this part manually worked for me

**Comment by ilkin0** [comment]
Thanks a lot. it works for now. im gonna check for what u mentioned.

**Comment by Linseneintopf** [comment]
Sorry for not reacting to your issue and comments. The initial issue has been fixed by #7, and the other problem was hopefully resolved by #8. Thank you to [FedericoHeichou](https://github.com/FedericoHeichou) and [safaber01](https://github.com/safaber01) for submitting these pull requests.
