### ISSUE TITLE
./scripts/download_images.sh: 12: ./read_decklist.sh: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by FaizeRPG** [Linseneintopf/ygo-proxy-generator#5]
For Ubuntu users, remind to change /bin/sh with /bin/bash to correct this error in /scripts/*.sh  files.

**Comment by Linseneintopf** [comment]
Sorry for not reacting. Thank you to [FedericoHeichou](https://github.com/FedericoHeichou) and [safaber01](https://github.com/safaber01) who have independently submitted pull requests for this.

Fixed by #7
