### ISSUE TITLE
Inconsistent number of images per page

### ISSUE THREAD

**Issue by jonathanluepfert** [Linseneintopf/ygo-proxy-generator#6]
The proxies.pdf has only 6 images per page instead of 9 on some pages. This can be verified with the sample Dark Warrior Danger Orcust decklist.

**Comment by Linseneintopf** [comment]
Sorry for not reacting to your issue. Unfortunately, I was unable to reproduce the problem.

**Comment by Linseneintopf** [comment]
I was able to reproduce the issue with another deck list. It should now be fixed.
